services:
  - type: web
    name: firsttask-backend
    env: python
    buildCommand: cd server && pip install -r requirements.txt
    startCommand: cd server && gunicorn app:app
    envVars:
      - key: GMAIL_EMAIL
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: OWNER_EMAIL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11
    disk:
      name: submissions-db
      mountPath: /opt/render/project/src/server
      sizeGB: 1

  - type: web
    name: firsttask-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://firsttask-backend.onrender.com

